# This file lists the minimal dependencies needed to build the documentation
# for sage-flatsurf. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -n sage-flatsurf-docbuild -f ../environment.yml
# conda env update -n sage-flatsurf-docbuild -f environment.yml
name: sage-flatsurf-docbuild
channels:
  - conda-forge
dependencies:
  # The sphinx integration of SageMath 10.0 relies on an older version of Sphinx.
  - sphinx>=5,<6
  - myst-nb
  - tachyon
  - furo
